### ISSUE TITLE
Not working with react

### ISSUE THREAD

**Issue by neondeex** [deinsoftware/vscode-arrow-snippets#1]
![image](https://user-images.githubusercontent.com/30392593/151009651-60712582-e72c-410b-8356-65c426225de8.png)
As you can see here if i use it inside react return i don't get the suggestions but if i use it on the outside i did
![image](https://user-images.githubusercontent.com/30392593/151009844-9e5485bb-2778-4056-bfa5-d6a2656d69d6.png)

**Comment by equiman** [comment]
It works on my machine 🤷‍♂️. **It's a Joke 😅**
![image](https://user-images.githubusercontent.com/933393/151020140-0619da04-ea37-407e-91db-cd7e0ef86768.png)

The only difference that I can see is that my example does not have a return. 
Could you please upload here your License component code to make some experiments? 🧪

**Comment by neondeex** [comment]
`import React from "react";
import { toast } from "react-toastify";
import React, { useState } from 'react';

const Lisence = () => {
  const [Celda, setCelda] = useState();
  
  return (
    <div>
      <div className="font-bold text-9xl text-mor">Emiliano</div>
      <div className="flex justify-center mt-9">
        <input
          className="inline-block px-2 py-4 text-sm border-2 bg-neg border-gri text-gri rounded-l-md focus:outline focus:outline-none focus:border-mor text-bla placeholder:text-lg w-60 " 
          type="password"
          placeholder="Lisence key" onChange={}
        />
        <button
          className="inline-block w-20 px-4 py-3 font-bold uppercase bg-mor text-bla text-md rounded-r-md"
          onClick={() => {
            const resolveAfter3Sec = new Promise((resolve, reject) => {
              if (afa)
                
            });
            toast.promise(resolveAfter3Sec, {
              pending: "Ingresando...",
              success: "Ingresado!",
              error: "Lisencia incorrecta!",
            });
            
          }}
        >LOGIN
        </button>
        <button />
      </div>
      <div className="flex justify-center mt-4">
        {/* <button className="inline-block px-10 py-3 font-bold uppercase bg-mor text-bla text-md rounded-l-md w-50">
          INVITADO
        </button>
        <button />
        <button className="inline-block px-10 py-3 font-bold uppercase bg-neg text-bla text-md rounded-r-md ww-50">
          COMPRAR
        </button>
        <button /> */}
      </div>
    </div>
  );
};

export default Lisence;
`

**Comment by neondeex** [comment]
`import React from "react";
import { toast } from "react-toastify";
import React, { useState } from 'react';

const Lisence = () => {
  const [Celda, setCelda] = useState();
  
  return (
    <div>
      <div className="font-bold text-9xl text-mor">Emiliano</div>
      <div className="flex justify-center mt-9">
        <input
          className="inline-block px-2 py-4 text-sm border-2 bg-neg border-gri text-gri rounded-l-md focus:outline focus:outline-none focus:border-mor text-bla placeholder:text-lg w-60 " 
          type="password"
          placeholder="Lisence key" onChange={}
        />
        <button
          className="inline-block w-20 px-4 py-3 font-bold uppercase bg-mor text-bla text-md rounded-r-md"
          onClick={() => {
            const resolveAfter3Sec = new Promise((resolve, reject) => {
              if (afa)
                
            });
            toast.promise(resolveAfter3Sec, {
              pending: "Ingresando...",
              success: "Ingresado!",
              error: "Lisencia incorrecta!",
            });
            
          }}
        >LOGIN
        </button>
        <button />
      </div>
      <div className="flex justify-center mt-4">
        {/* <button className="inline-block px-10 py-3 font-bold uppercase bg-mor text-bla text-md rounded-l-md w-50">
          INVITADO
        </button>
        <button />
        <button className="inline-block px-10 py-3 font-bold uppercase bg-neg text-bla text-md rounded-r-md ww-50">
          COMPRAR
        </button>
        <button /> */}
      </div>
    </div>
  );
};

export default Lisence;
`

**Comment by neondeex** [comment]
[Lisence.txt](https://github.com/deinsoftware/vscode-arrow-snippets/files/7935793/Lisence.txt)

**Comment by neondeex** [comment]
change the type to jsx

**Comment by equiman** [comment]
It's still working. I think could be something related to your VScode configuration. 

![image](https://user-images.githubusercontent.com/933393/151036496-c269b203-61fb-4b15-a3b0-6d67ba4cc074.png)

![image](https://user-images.githubusercontent.com/933393/151036535-42e3ab65-4905-43f0-a7b4-e2d3f3c84245.png)

![image](https://user-images.githubusercontent.com/933393/151036562-2593973c-3aa9-438e-b319-8af4f241a7b3.png)

![image](https://user-images.githubusercontent.com/933393/151036630-be33d26b-91cc-4d4b-93bc-f95ef527ee24.png)

Have you tried if happens the same with other snippet extensions?
Like: https://marketplace.visualstudio.com/items?itemName=dsznajder.es7-react-js-snippets

The only thing I see is on the bottom bar: snippets (not only this extension) only work until finish loading the language features. 
![image](https://user-images.githubusercontent.com/933393/151037239-97baebb6-d3c5-466f-8b0d-704dbd7ba943.png)

**Comment by neondeex** [comment]
![image](https://user-images.githubusercontent.com/30392593/151040723-7af0b74c-6ed7-4d77-906c-93739eca4bc5.png)
![image](https://user-images.githubusercontent.com/30392593/151040841-dd2cd2f9-ce12-4d09-98ae-b3b3af4d9ae4.png)
Found this
Where the snippet gets detected is because my editor detect javascript but hen it detects jsx-attr i don't get any snippets

**Comment by neondeex** [comment]
![image](https://user-images.githubusercontent.com/30392593/151041456-b1cf4780-66d3-44e4-bd21-aa78ab28b3f3.png)
and btw i  can't also use react snippets here but that's ok

**Comment by neondeex** [comment]
![image](https://user-images.githubusercontent.com/30392593/151060819-92d2dbcb-3f52-434c-a1ed-0711c6358125.png)
Just did a work around created a jsx-attr.json snippet file and paste all the snippets hope to see a fix on the extension

**Comment by equiman** [comment]
What tool do you use to see this information to display the language and the other things?



Sorry. I didn't catch the annotation about the `jsx-attr.json` could you please explain it better?

That's because snippets extensions have a list of approved [language identifiers](https://code.visualstudio.com/docs/languages/identifiers) and actually this extension is compatible with JS, TS, JSX, and TSX.

![image](https://user-images.githubusercontent.com/933393/151079601-1ca4edc2-e6a6-46ea-ad0c-fd0e1156c553.png)
![image](https://user-images.githubusercontent.com/933393/151079626-d53afe6b-f5a6-430d-b36d-fcaedc2ef195.png)

But I didn't see on the language list, something related to JSX Attr.

**Comment by neondeex** [comment]
ctrl + shift + p > Inspect scope
Then the annotation means that just in the part where I have my react HTML is jsx-attr lenguage so thats, why this extension is not working since my editor, autodetects the language and give you smart suggestions. So the work around was downloading the snippets from github to add them to the snippet file for jsx-attr language so this was a manual way

**Comment by equiman** [comment]
I will add `jsx-attr` as language in a new version.

![image](https://user-images.githubusercontent.com/933393/151211528-d4ce993c-285b-4a2c-96e9-1322108bdff6.png)

**Comment by equiman** [comment]
I've published the 1.7.1 version. Could you please test if it solves the problem?

**Comment by neondeex** [comment]
![image](https://user-images.githubusercontent.com/30392593/151214925-d0578a5e-740d-464e-bcba-c36133487773.png)
Working!
Nice job

**Comment by equiman** [comment]
Excellent, thanks for your detailed report and help.

Last thing. Which version of VS Code are you using?

**Comment by neondeex** [comment]
1.62.0-1

**Comment by equiman** [comment]
Well, we are using almost the same, maybe the problem is that the documentation is not updated. 

Again thanks for your help!

**Comment by neondeex** [comment]
Sure!
