### ISSUE TITLE
afc (with currly brackets)

### ISSUE THREAD

**Issue by jobe451** [deinsoftware/vscode-arrow-snippets#2]
Thanks for these awesome snipptes. The one I would need most, is missing. 

That is really a minor issues, the same can be achieved with "afe" and deleting the return of course.

afc (with currly brackets);
```javascript
() => {
    █
}
```

**Comment by equiman** [comment]
`1.8.0` version was released 😎

I've included it under the name of `afee`  (arrowFunctionExplicitEmpty) to preserve the "arrow function explicit" naming convention when using curly brackets.

**Comment by jobe451** [comment]
Thanks a lot!!!! Awesome!

**Comment by equiman** [comment]
@jobe451 definitely you are right from the beginning. 
I've been using `cv` + `afee` too much and it's really annoying to use two snippets for that. 

So, today I decided to add a shortcut with: 
- `caf` constant arrow function
- `caft` constatn arrow function with return type (typescript)

Version 1.9.0 is available.
