### ISSUE TITLE
Feature request: add snippets for `async` functions

### ISSUE THREAD

**Issue by OneHoopyFrood** [deinsoftware/vscode-arrow-snippets#3]
This is a feature request to include some snippets for async functions.

If I get some time I'll submit a PR. 

Thanks for the extention! Just what I've been needing!

**Comment by equiman** [comment]
Actually, we have various snippets that use async.

Please https://github.com/deinsoftware/vscode-arrow-snippets#functions

Did you have a specific snippet to add?

**Comment by equiman** [comment]
Missing information.
