### ISSUE TITLE
Request: Restore "afee" and "afeea" snippets

### ISSUE THREAD

**Issue by jagiles-ren** [deinsoftware/vscode-arrow-snippets#9]
In the most recent release, these snippets were removed with the note that they could use the snippets with return, with the additional step of deleting the return if the return is not necessary. In practice, this has the unintended consequence of making intellisense unusable until the escape key or tab key is pressed in addition to the backspace key since the `return` keyword is highlighted as part of the snippet. 

I fully realize that this is a minor inconvenience, but the "afee" template was one I used quite frequently, especially when writing unit tests. I have found myself tripping over this time and time again in the days since this template was removed.

**Comment by equiman** [comment]
Hi @jagiles-ren thank you for your report and feedback. We will try to take a look tonight.

**Comment by equiman** [comment]
Done, snippets were restored! v3.1.0

**Comment by jagiles-ren** [comment]
Thanks @equiman! You are my hero

**Comment by equiman** [comment]
You welcome!
